name: DungeonMaze
main: com.timvisee.dungeonmaze.DungeonMaze
version: 0.1.8
load: startup
softdepend: [Multiverse-Core, PermissionsBukkit, Permissions, PermissionsEX, EssentialsGroupManager]
commands:
  dm:
    description: Dungeon Maze command
    usage: /dm
  dungeonmaze:
    description: Dungeon Maze command
    usage: /dungeonmaze